# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
fail_fast: true
exclude: ^.vscode/$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        exclude: ".*\\.ipynb$"
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: debug-statements
      - id: check-case-conflict
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.259
    hooks:
      - id: ruff
        exclude: "^.*test(s)?/|__init__"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/doublify/pre-commit-rust
    rev: "v1.0"
    hooks:
      - id: clippy
        name: clippy-2016 # do it this ugly way until i learn Rust packaging
        args:
          [
            "--manifest-path",
            "aoc_solvings/src_2016/Cargo.toml",
            "--",
            "-D",
            "warnings",
            "-D",
            "clippy::pedantic",
            "-D",
            "clippy::nursery",
            "-D",
            "clippy::all",
          ]
